/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  mice                                   */
/*      FILE         :  mice.c                                 */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  SH-2                                   */
/*      CPU TYPE     :  SH7125                                 */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/
#include"mice.h"

volatile void main(void) {

		input_daikei(150, 500, 2700, 1000);
	 velocity = velocity_min;
	 tmp_accelerate = accelerate;
	 distance_sankaku = (velocity_max * velocity_max
	 - velocity_min * velocity_min) / (2 * accelerate);

	init_sci1();
	init_all();

	AD_BATTERY();

	Battery = 5.0 / 1024.0 * BAT * 151.0 / 51.0;
	myprintf("Battery=%d\n\r", Battery);

	CMT.CMSTR.BIT.STR0 = 1; //CMT0カウントスタート

	while (1) {
		AD_BATTERY();
		//turn(300,20);
		Battery = 5.0 / 1024.0 * BAT * 151.0 / 51.0;
		myprintf("Battery=%d\n\r", Battery);
		if (Battery > 9) {
			while (1) {
				while (1) {
					if (SW_YELLOW == 0) {
						wait_ms(500);
						sw_1++;
					}
					if (sw_1 == 1) {
						led_red = 1;
					} else if (sw_1 == 2) {
						led_green = 1;
						led_red = 0;
					} else if (sw_1 == 3) {
						led_red = 1;
						led_green = 1;
					} else if (sw_1 == 4) {
						led_red = 0;
						led_green = 0;
					}else if(sw_1 ==5){
						sw_1 = 1;
					}
					if (SW_BROWN == 0) {
						wait_ms(500);
						break;
					}

				}
				switch (sw_1) {
				case 1:
					motor_driver_reset = 1; //Motor Driver Reset
					wait_ms(1);

					motor_driver_reset = 0; //Motor Driver Reset解除
					wait_ms(10);

					motor_enable = 1; //Motor Enable=1,励磁条件
					wait_ms(1000);
					//daikei(150, 500, 2700, 1000);
					MTU2.TSTR.BIT.CST0 = 1; //9.3.14 タイマスタートレジスタ(TSTR)TCNT0動作
					MTU2.TSTR.BIT.CST1 = 1; //動作TCNT1動作

					//hidariteho();
					adatiho();
					//accel_valocity(150, 300, 300, 180, 2000);
					//circuit(15);
					MTU2.TSTR.BIT.CST0 = 0; //9.3.14 タイマスタートレジスタ(TSTR)TCNT0動作
					MTU2.TSTR.BIT.CST1 = 0; //動作TCNT1動作
					//daikei(150, 500, 720, 1000);

					sw_1 = 0;
					break;
				case 2:
					motor_driver_reset = 1; //Motor Driver Reset
					wait_ms(1);

					motor_driver_reset = 0; //Motor Driver Reset解除
					wait_ms(10);

					motor_enable = 1; //Motor Enable=1,励磁条件
					wait_ms(1000);
					MTU2.TSTR.BIT.CST0 = 1; //9.3.14 タイマスタートレジスタ(TSTR)TCNT0動作
					MTU2.TSTR.BIT.CST1 = 1; //動作TCNT1動作

					saitan();

					MTU2.TSTR.BIT.CST0 = 0; //9.3.14 タイマスタートレジスタ(TSTR)TCNT0動作
					MTU2.TSTR.BIT.CST1 = 0; //動作TCNT1動作

					sw_1 = 0;
					break;
				case 3:

					motor_enable = 0;
					while (1) {
						if (T % 300 == 0) {
							myprintf("SENleft_offset=%d\t", SENleft_offset);
							myprintf("SENfrontleft_offset=%d\t", SENfrontleft_offset);
							myprintf("SENright_offset=%d\t", SENright_offset);
							myprintf("SENfrontright_offset=%d\n\r",
									SENfrontright_offset);
						}

						if (T % 50000 == 0) {
							break;
						}
					}
					sw_1 = 0;
					break;
				case 4:
					//test_map();
					motor_enable = 1; //Motor Enable=1,励磁条件
					wait_ms(1000);

					MTU2.TSTR.BIT.CST0 = 1; //9.3.14 タイマスタートレジスタ(TSTR)TCNT0動作
					MTU2.TSTR.BIT.CST1 = 1; //動作TCNT1動作

					accel_velocity(150, 500, 500, 90, 2000);


					slalom_right(500 , 20 , 1000 , 90);

					slalom_left(500 , 20 , 1000 , 90);

					accel_velocity(500, 150, 500, 90, 2000);

					MTU2.TSTR.BIT.CST0 = 0; //9.3.14 タイマスタートレジスタ(TSTR)TCNT0動作
					MTU2.TSTR.BIT.CST1 = 0; //動作TCNT1動作

					//map_path();
					/*motor_driver_reset = 1; //Motor Driver Reset
					 wait_ms(1);

					 motor_driver_reset = 0; //Motor Driver Reset解除
					 wait_ms(10);

					 motor_enable = 1; //Motor Enable=1,励磁条件
					 wait_ms(1000);
					 MTU2.TSTR.BIT.CST0 = 1; //9.3.14 タイマスタートレジスタ(TSTR)TCNT0動作
					 MTU2.TSTR.BIT.CST1 = 1; //動作TCNT1動作

					 //tyousinti_left(150, 300, 90, 1000);

					 MTU2.TSTR.BIT.CST0 = 0; //9.3.14 タイマスタートレジスタ(TSTR)TCNT0動作

					 MTU2.TSTR.BIT.CST1 = 0; //動作TCNT1動作*/
					sw_1 = 0;
					break;
				default:

					break;

				}
				break;


			}

		} else {
			Led_Twinkle();
		}


	}
}
